Add VPA for policy-reporter
giantswarm/kyverno-app pull request #193
Opened 2022-11-24 10:50 UTC by fhielpos

2022-11-24 13:04 UTC, stone-z commented on helm/kyverno/charts/policy-reporter/values.yaml
> +  # fullnameOverride: ""
What's the story here?

2022-11-24 15:42 UTC, fhielpos commented on helm/kyverno/charts/policy-reporter/values.yaml
> +  # fullnameOverride: ""
I had issues with the templating but switched the approach already

2022-11-25 16:03 UTC, fhielpos commented
I'm pretty confident on deploying this "as is", but would like to have the proper templating on the subcharts deployments.

2022-11-29 11:25 UTC, rewanthtammana requested changes

2022-11-29 11:25 UTC, rewanthtammana commented on helm/kyverno/values.yaml
> +  enabled: true
Do we want to enable this option by default? Like Stefan mentioned, we disabled it for falco & enabled it for trivy based on the criticality of the applications. It might be better to disable it for kyverno, but not really sure.

2022-11-29 11:26 UTC, fhielpos commented on helm/kyverno/values.yaml
> +  enabled: true
I'm not too concerned since this is for `policy-reporter` and `ui` only, but will keep it disabled.

2022-11-29 11:34 UTC, rewanthtammana commented on helm/kyverno/templates/vpa/vpa-policyreporter.yaml
> +    - containerName: '*'
Do we have a single container per pod in kyverno or do we have any side cars attached to it? because if kyverno deployment/pod is having more than one container, the VPA will be applied to all containers & it might be an issue.

2022-11-29 11:35 UTC, rewanthtammana commented on helm/kyverno/templates/vpa/vpa-policyreporter.yaml
> +    - containerName: '*'
If we have multiple containers in kyverno ui/policy reporter pods, it's better to mention the name of the container rather than having '*'

2022-11-29 11:37 UTC, fhielpos commented on helm/kyverno/templates/vpa/vpa-policyreporter.yaml
> +    - containerName: '*'
Both are single container pods 😄

2022-11-29 11:39 UTC, rewanthtammana commented on helm/kyverno/templates/vpa/vpa-policyreporter.yaml
> +    - containerName: '*'
Awesome

2022-11-29 11:39 UTC, rewanthtammana approved these changes
LGTM

2022-11-29 11:53 UTC, merged