Changed the crd-install job to use the  flag in its  command.
giantswarm/kyverno-app pull request #307
Opened 2023-11-14 13:21 UTC by Strigix

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

2023-11-14 13:23 UTC, fhielpos commented
Update your branch please, you are one version behind in your changelog.

2023-11-14 13:24 UTC, fhielpos requested changes

2023-11-14 13:24 UTC, fhielpos commented on CHANGELOG.md
>  - Removed unused values and update schema.
This has been released already, you need to rebase.

2023-11-14 13:25 UTC, Strigix commented on CHANGELOG.md
>  - Removed unused values and update schema.
How, I just created the branch from main 😂 , but sure.

2023-11-15 13:24 UTC, fhielpos approved these changes

2023-11-15 13:24 UTC, merged