Policy wildcards should be restricted by GVK
giantswarm/kyverno-app pull request #433
Opened 2024-08-17 06:53 UTC by mproffitt

Crossplane introduces types of `Policy` which are not related to kyverno but get blocked by the wildcard policy which then does not understand them.

To support crossplane co-existing, this change restricts the wildcard policy to the GVK for types Policy and ClusterPolicy

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

2024-08-17 17:20 UTC, fhielpos requested changes

2024-08-17 17:20 UTC, fhielpos commented on CHANGELOG.md
> +- Restrict Policy and ClusterPolicy to kyverno.io/v1 for wildcard policy matching
Can you move this under the `changed` section?

2024-08-17 18:58 UTC, mproffitt commented on CHANGELOG.md
> +- Restrict Policy and ClusterPolicy to kyverno.io/v1 for wildcard policy matching
done

2024-08-17 18:58 UTC, fhielpos approved these changes
LGTM

2024-08-18 14:39 UTC, fhielpos commented
PS: Tests will fail because of a CRD change. Don't worry about it.

2024-08-19 08:11 UTC, merged